### PR TITLE
update returnBytes

### PR DESCRIPTION
**Pull request by vsotirasqmplus**
avoid warning on string to text multiplication on PHP7

### CODE REVIEW

**Comment by thomasmars** [comment]
Could you explain why this fixes the warning ? What was your initial value for $val when you got the warning ?As far as I can see the $bytes should always be casted to int before any multiplication is done, unless there are multiple characters at the end of the string for the magnitude.

**Comment by vsotirasqmplus** [comment]
There is a warning recorded under PHP 7 and the casting is making sure there are no unnecessary warning log entries in the web server. Have you tried it with PHP 7 and full warnings reporting? You will see for yourself the message too. We try to keep the logs as clear as possible. This is a warning that could be removed.

See here http://php.net/manual/en/migration71.other-changes.php

**Comment by thomasmars** [comment]
Hi,
Sorry if I came off blunt, I'll try to explain the problem better.

The reason I'm asking is that I have tested with PHP 7.0. I'm not getting the message and i suspect it is because it depends on the input it gets, the `$val` argument that returnBytes() gets in.
 
The problem with your solution is that the input to this function is usually a number with a unit at the end, so it is a string, not a pure int. For instance my input to the function is `150M`, the max size that is allowed to be uploaded to my server, set in my php.ini file.

When you run `(int) trim($val)` on `150M` you're effectively removing the unit from it, causing it to be casted to `150`. When you lose the unit it will just return 150 when translating the bytes, when in fact the total bytes returned should be `150*1024*1024 = 157,286,400*. This will make all logic depending on this value fail as well.

Could you please check what the value of `upload_max_filesize` and `post_max_size` is set to in your php.ini so that we can figure out a better way to solve this and remove the warning ?

Thanks

**Comment by vsotirasqmplus** [comment]
Dear Thomas,

As this was a side task I had to go through to have an error free Moodle installation, I realised the current version is not as the one was provided to us.

Look, the version I am working states the function as this:

  /**
   * Return bytes from php_ini string value
   *
   * @param string $val
   *
   * @return int|string
   */
  public static function returnBytes($val) {
    $val  = trim($val);
    $last = strtolower($val[strlen($val) - 1]);
    switch ($last) {
      case 'g':
        $val *= 1024;
      case 'm':
        $val *= 1024;
      case 'k':
        $val *= 1024;
    }

    return $val;
  }


Which is clear why there is a warning in PHP7. 

I realise the version I edited has gone away from this coding style, and yes you are correct in the new version, and I was working on an erroneous version and I have to inform the system administrators to confirm the version they provides us in the Moodle build.

So you can clearly ignore the suggestion for this version, as I have been given an earlier one.

Sincerely

Vasileios

**Comment by falcon-git** [comment]
Thomas is on vacation, but it seems there is no more action needed here? Thanks for posting the explanation

**Pull request closed without merging**
