### PR TITLE
Fix: Author comments can contain linebreaks

### PR DESCRIPTION
**Pull request by JsBergbau**
Author comments can contain line breaks, fixing that validation failed so far.

For more details see https://github.com/h5p/h5p-php-library/issues/96

### CODE REVIEW

**Comment by JsBergbau** [comment]
@h5p. This pull request is open for more than one year now. Can you please check and merge the improvement?

**Comment by otacke** [comment]
@JsBergbau I guess given that https://github.com/h5p/h5p-php-library/pull/109/files fixed the issue as well (including the log and the license extras with the same problem), you could simply close your pull request.

**Comment by JsBergbau** [comment]
Thanks for your fast answer. Since https://github.com/h5p/h5p-php-library/pull/109/ was merged it is indeed not needed anymore. However interesting that your Pull request was merged after two month, whereas this pull request was almost 11 month earlier and didn't get merged.

**Comment by otacke** [comment]
@JsBergbau I don't know how pull requests are handled. If I remember correctly, I may have hinted to mine on some other channel.

**Pull request closed without merging**
